### PR TITLE
Add Avatar of Death and Giant Fly

### PR DESCRIPTION
**Pull request by txtsd**
## What does this do?
Adds the Avatar of Death and Giant Fly. They were missing because they were listed under Magic Items.

## How was it tested?
Added manually.

## Is there a Github issue this is resolving?
No, but mentioned here #299 

## Did you update the docs in the API? Please link an associated PR if applicable.
No

## More
Things that are different from the norm:
For `Avatar of Death`: 
`"hit_points": "half the hit point maximum of its summoner"`
 `hit_dice` missing
`"challenge_rating": "—",` like in the SRD. Should I make it 0?
For `Giant Fly`:
`challenge_rating` and `actions` and `special_abilties` are missing

### CODE REVIEW

**Comment by bagelbits** [comment]
For `Giant Fly`, CR is most likely 0. And `actions` and `special_abilities` are missing because it has none.

For `Avatar of Death`, wow. That's.... that's really weird. I almost want to not even put that in here because of how weird it is and leave it in Magic Items.

**Comment by Redmega** [comment]
The Giant Fly only comes from `Figurine of Wondrous Power` (A magical item) and is also lacking a CR and XP entry in the SRD

**Comment by bagelbits** [comment]
I'm honestly okay if we just add neither?

**Comment by txtsd** [comment]
Fair enough. I'll leave this here anyway in case we change our minds.

**Pull request closed without merging**
