### PR TITLE
Simple JSON clean up of Monsters

### PR DESCRIPTION
**Pull request by bagelbits**
## Overview
Any more JSON cleanup I'm going to do is going to be easier without these polluting it.

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Curious if you are doing this by hand or if you are using some scripts to process this into a better format.

**Comment by bagelbits** [comment]
I'm using Prettify JSON within VS Code.

**Comment by benjaminapetersen** [comment]
Ah, so not a script to reformat the structure (vs by hand adjustments to all 300-ish monster entries).

**Comment by bagelbits** [comment]
Yeah. Doing by hand adjustments is not a fun time if I can avoid it. But it is what I had to do with adding all of the attack info for monster abilities.

**Pull request merged**
