### PR TITLE
feat: Adding Totem Warrior subclass

### PR DESCRIPTION
**Pull request by bjvargas**
Adding subclass Totem Warrior to Barbarian.

## What does this do?

Its the second path to the barbarian class at 3rd level.

## How was it tested?

In my local application.

## Is there a Github issue this is resolving?
no

### CODE REVIEW

**Comment by bjvargas** [comment]
https://github.com/5e-bits/5e-database/pull/542
https://github.com/5e-bits/5e-database/pull/543
https://github.com/5e-bits/5e-database/pull/544
https://github.com/5e-bits/5e-database/pull/545

**Comment by bagelbits** [comment]
Totem Warrior isn't actually in the SRD even though it is briefly mentioned. Only Path of the Berserker is fully in there. So, I don't think we can add this to the DB.

**Comment by bjvargas** [comment]
Alright, I did some research and understood what the SRD is; I thought it was the same version as the book. However, this feature mentions the Totem, so maybe we should consider updating it? If so, please point me to the source they use from the SRD, so I can make the changes and contribute to the project. Thank you.

  {
    "index": "primal-path",
    "class": {
      "index": "barbarian",
      "name": "Barbarian",
      "url": "/api/classes/barbarian"
    },
    "name": "Primal Path",
    "level": 3,
    "prerequisites": [],
    "desc": [
      "At 3rd level, you choose a path that shapes the nature of your rage. Choose the Path of the Berserker or the Path of the Totem Warrior, both detailed at the end of the class description. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels."
    ],
    "url": "/api/features/primal-path"
  }

**Comment by adrpadua** [comment]
It doesn’t exist in the SRD despite being mentioned. I assume you pulled the data from the Players Handbook right?

Regardless, this is a really great effort to add the subclass and would be a great resource for your personal database, however like @bagelbits said it can’t be added to the database due to being taken from the PHB

**Comment by bjvargas** [comment]
Exactly! But, check this feature that **already** is in database:
In the description says: "Choose the Path of the Berserker or the Path of the Totem Warrior". Is this information from SRD or Players Handbook?

{
"index": "primal-path",
"class": {
"index": "barbarian",
"name": "Barbarian",
"url": "/api/classes/barbarian"
},
"name": "Primal Path",
"level": 3,
"prerequisites": [],
"desc": [
"At 3rd level, you choose a path that shapes the nature of your rage. Choose the Path of the Berserker or the Path of the Totem Warrior, both detailed at the end of the class description. Your choice grants you features at 3rd level and again at 6th, 10th, and 14th levels."
],
"url": "/api/features/primal-path"
}

**Comment by fergcb** [comment]
> Is this information from SRD or Players Handbook?

This information is from page 9 of the SRD. The _descriptions_ of those subclasses are not in the SRD, however.

**Comment by fergcb** [comment]
> please point me to the source they use from the SRD

https://www.dndbeyond.com/attachments/39j2li89/SRD5.1-CCBY4.0_License_live%20links.pdf

**Pull request closed without merging**
