### PR TITLE
Quality of Life and Multiattack Improvements for Monsters.json (Part 1 of 3)

### PR DESCRIPTION
**Pull request by caldane**
Monster Update from 
**Aboleth**
to
**Frost Giant**

### CODE REVIEW

**Comment by caldane** [comment]
This is a break up of the PR144 into 3 smaller PR's:
so that we can use the online git tools to manage the diff.

https://github.com/bagelbits/5e-database/pull/144

**Comment by ogregoire** [comment]
I disagree with the "quality of life" point.

It might be easier for *your* language to parse everything and keep everything structured. In some other languages, specially the null hostile languages (which become more and more used, btw), having a value set to null is harder to parse.

Semantics matter here, and the absence of something is not the same as a dummy mapping.

So I would prefer to keep the data as is, put it there when it's present in the SRD, and avoid it when it's not present. Just like the SRD did: WotC didn't give legendary actions to all mobs but make it really useful only on a subset of them, they put it there when needed.

That's my opinion. Others might differ.

**Comment by ogregoire** [comment]
However, I would prefer that you split your PRs in two not based on lengths but based on topic: one for the QoL and another for the multi-attack.

**Comment by caldane** [comment]
@ogregoire thank you for the feedback, I would love to chat with you about the most ideal way to do this.  Are you in the api discord?

**Pull request closed without merging**
