### PR TITLE
Update incorrect damage type,dice,bonus for attacks with secondary rolls

### PR DESCRIPTION
**Pull request by caldane**
Update the damage type,dice,bonus for attacks with secondary rolls for the following monsters:

- Adult Black Dragon
- Adult Blue Dragon
- Adult Green Dragon
- Adult Red Dragon
- Adult White Dragon
- Ancient Black Dragon
- Ancient Blue Dragon

### CODE REVIEW

**Comment by AndruC** [comment]
Normally I'd recommend splitting this into two PRs, since the damage type is a fix unrelated to the Enlarge/Reduce spell.

**Comment by AndruC** [comment]
> Normally I'd recommend splitting this into two PRs, since the damage type is a fix unrelated to the Enlarge/Reduce spell.

Just noticed that Enlarge/Reduce was fixed in another PR

**Comment by bagelbits** [comment]
@caldane I think you need to rebase/merge your fork with the main repo. Otherwise, it's including the same change from your previous PR.

**Comment by caldane** [comment]
I see my fault guys. Still new to github, my introduction to git was azure dev ops.  Also I have always been on a team where I am a contributor so I have not needed to fork, I will not make that mistake again.

**Comment by caldane** [comment]
@AndruC @bagelbits 
Ok I rebased and now we are only seeing the changes from the PR in question.

**Review by bagelbits — APPROVED** [review]
LGTM

**Pull request merged**
