### PR TITLE
Add multiclassing models for classes.

### PR DESCRIPTION
**Pull request by Arnoldave**
## What does this do?
This adds multi-classing data to the class definitions. I made this a while ago; thought I might as well throw up a PR, see what you guys think.

## How was it tested?
Same as always; I just build the image in Docker, and then check that the data I added is there.

## Is there a Github issue this is resolving?
Not that I know of. Just another case of missing data I spotted.

## Did you update the docs in the API? Please link an associated PR if applicable.
Not yet; will do it when I make the changes to the API.

## Here's a fun image for your troubles
random photo - update me

### CODE REVIEW

**Comment by bagelbits** [comment]
That looks pretty good. I'm going to let this marinate for a bit and see if anyone else has any feelings on it. The `prerequisite_options` is weird but I get why it's there. Damn Fighters.

**Comment by Arnoldave** [comment]
> That looks pretty good. I'm going to let this marinate for a bit and see if anyone else has any feelings on it. The `prerequisite_options` is weird but I get why it's there. Damn Fighters.

I totally agree with you about prerequisite options. I'm fully open to any suggestions if you come up with any.

**Comment by bagelbits** [comment]
Honestly, I think you've made the right choice. It's just the SRD that's weird.

**Comment by bagelbits** [comment]
Apparently I let it marinate for too long. 😅 

I'll get this merged in.

**Pull request merged**
