### PR TITLE
Fix: Misc. Incorrect Monster Data

### PR DESCRIPTION
**Pull request by Redmega**
## What does this do?
Fixes some mismatched data between the SRD and what exists in the DB

## How was it tested?
CI/CD

## Is there a Github issue this is resolving?
No, this was reported on our site

## Did you update the docs in the API? Please link an associated PR if applicable.
No docs to update

## Here's a fun image for your troubles
random photo - update me

### CODE REVIEW

**Comment by Redmega** [comment]
Horned Devil:
Screenshot from 2020-10-27 11-35-59

Wight:
Screenshot from 2020-10-27 11-38-22

**Review by ogregoire — APPROVED** [review]

**Comment by ogregoire** [comment]
Note, it might be good at some point to reformat the file properly. Too many `"damage_immunities": ["fire", "whatever"]` exist and aren't properly formatted.

**Comment by Redmega** [comment]
> aren't properly formatted

Are you referring to them not being APIResource docs w/ url, etc?

**Comment by ogregoire** [comment]
That crossed my mind as well, but I was more literal by thinking about pure formatting and indentation.

**Comment by bagelbits** [comment]
@ogregoire For the most part, I have an autoformatter handle it but having any kind of standard configuration on it wouldn't be a terrible idea.

**Comment by bagelbits** [comment]
#246 is for figuring out how to handle API Resources for that. The `"whatever"` is the troubling part of that.

**Review by bagelbits — APPROVED** [review]
LGTM!

**Pull request merged**
